version: '3.8'

services:
  mongodb:
    image: mongo:7.0
    container_name: biblioteca-mongo
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    environment:
      MONGO_INITDB_DATABASE: biblioteca
    networks:
      - biblioteca-net

  sonarqube:
    image: sonarqube:10-community
    container_name: biblioteca-sonarqube
    restart: unless-stopped
    ports:
      - "9000:9000"
    environment:
      SONAR_ES_BOOTSTRAP_CHECKS_DISABLE: "true"
    volumes:
      - sonar-data:/opt/sonarqube/data
      - sonar-logs:/opt/sonarqube/logs
    networks:
      - biblioteca-net

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: biblioteca-backend
    restart: unless-stopped
    ports:
      - "8080:8080"
    environment:
      MONGODB_URI: mongodb://mongodb:27017/biblioteca
      JWT_SECRET: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
      JWT_EXPIRATION: 86400000
    depends_on:
      - mongodb
    networks:
      - biblioteca-net

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: biblioteca-frontend
    restart: unless-stopped
    ports:
      - "3000:80"
    depends_on:
      - backend
    networks:
      - biblioteca-net

volumes:
  mongo-data:
  sonar-data:
  sonar-logs:

networks:
  biblioteca-net:
    driver: bridge
